=== smarkwal/vtestmail/docs/xsd/mailbox-store-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="store" type="storeType"/>
    <xs:complexType name="storeType">
        <xs:sequence>
            <xs:element type="mailboxType" name="mailbox" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="mailboxType">
        <xs:sequence>
            <xs:element type="folderType" name="folder" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="email" use="required"/>
        <xs:attribute type="xs:string" name="secret" use="required"/>
        <xs:attribute type="xs:string" name="username" use="required"/>
    </xs:complexType>
    <xs:complexType name="folderType">
        <xs:sequence>
            <xs:element type="messageType" name="message" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="uidNext" use="required"/>
        <xs:attribute type="xs:string" name="uidValidity" use="required"/>
    </xs:complexType>
    <xs:complexType name="messageType">
        <xs:sequence>
            <xs:element type="xs:string" name="flag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="content"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="uid" use="required"/>
    </xs:complexType>
</xs:schema>

=== smarkwal/vtestmail/vtestmail-core/src/test/resources/mailbox-store.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://smarkwal.github.io/vtestmail/xsd/mailbox-store-1.0.0.xsd">
    <mailbox email="user1@localhost" secret="secret1" username="user1">
        <folder name="INBOX" uidNext="3" uidValidity="1">
            <message uid="1">
                <flag>\Flagged</flag>
                <flag>\Seen</flag>
                <content>Subject: Test 1[CRLF][CRLF]This is test message 1.</content>
            </message>
            <message uid="2">
                <content>Subject: Test 2[CRLF][CRLF]This is test message 2.</content>
            </message>
        </folder>
        <folder name="Drafts" uidNext="2" uidValidity="1">
            <message uid="1">
                <flag>\Draft</flag>
                <content>Subject: Test 3[CRLF][CRLF]This is a draft.</content>
            </message>
        </folder>
    </mailbox>
    <mailbox email="user2@localhost" secret="secret2" username="user2">
        <folder name="INBOX" uidNext="3" uidValidity="1">
            <message uid="1">
                <flag>\Answered</flag>
                <flag>\Seen</flag>
                <content>Subject: Test 1[CRLF][CRLF]This is test message 1.</content>
            </message>
            <message uid="2">
                <content>Subject: Test 2[CRLF][CRLF]This is test message 2.</content>
            </message>
        </folder>
        <folder name="Drafts" uidNext="1" uidValidity="1"/>
        <folder name="Trash" uidNext="2" uidValidity="1">
            <message uid="1">
                <flag>$Junk</flag>
                <flag>\Deleted</flag>
                <content>Subject: Test 3[CRLF][CRLF]This is spam.</content>
            </message>
        </folder>
    </mailbox>
    <mailbox email="user3@localhost" secret="secret3" username="user3"/>
</store>
